[main]
# 启用模块自动更新（在手机 Magisk 管理器中会收到新版本推送）
enable-module-update = true
# 并行任务数，手机端建议保持为 1 以免内存溢出
parallel-jobs = 1

remove-rv-integrations-checks = false

# Piko 补丁源（核心：指向 crimera/piko）
patches-version = "dev"
cli-version = "dev"
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Piko"

# 如果你想排除某些补丁（不常用，可以保持注释状态）
excluded-patches = ["Change-version-code"]

[Instagram]
enabled = true
app-name = "Instagram"

# 模式建议选 "both"，会同时生成 Magisk 模块和独立安装的 APK
build-mode = "both"

# 指定架构。目前绝大多数主流手机都是 arm64-v8a
arch = "arm64-v8a"

# 版本号建议先用 auto。如果构建失败，请改为具体的版本号（如 "321.0.0.40.101"）
version = "425.0.0.0.0"

# 下载源，脚本会自动去这个页面抓取最新的 APK
direct-dlurl = "https://github.com/dary1zhu/revanced-magisk-module/releases/download/Prebuilts/com.instagram.android-v425.apk"

# 模块在 Magisk 中显示的 ID 名
module-prop-name = "piko-instagram"
